# Generated by Django 2.2.3 on 2019-07-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix',
        ),
    ]
