# Generated by Django 2.2.5 on 2019-09-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20190920_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
