# Generated by Django 2.2.5 on 2019-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='exclusivite',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
