# Generated by Django 2.2.7 on 2019-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20191029_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prixVente',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
