# Generated by Django 2.2.7 on 2019-11-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_produit_prixvente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prixVente',
            new_name='prixFournisseur',
        ),
    ]
