# Generated by Django 2.2.7 on 2019-12-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20191121_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='codeProduitFournisseur',
            field=models.CharField(default='code', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='nomFournisseur',
            field=models.CharField(default='fo', max_length=200),
            preserve_default=False,
        ),
    ]
