# Generated by Django 3.0 on 2019-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20191206_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nbCreated', models.PositiveIntegerField(default=0)),
                ('nbDeleted', models.PositiveIntegerField(default=0)),
                ('nbModified', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
