# Generated by Django 3.0.1 on 2019-12-18 17:23

import application.djangoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='exclusivite',
            field=models.CharField(default=application.djangoapp.models.get_exclusivite, max_length=10),
        ),
    ]
