# Generated by Django 3.0.1 on 2020-01-13 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_auto_20191218_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
